"""
models/decision.py
------------------
Immutable audit records of automated safety decisions and natural language explanations.
"""

from enum import Enum
import uuid
from sqlalchemy import String, Float, Boolean, Text, ForeignKey, DateTime
from sqlalchemy.orm import Mapped, mapped_column, relationship
from core.database import Base, TimestampMixin


class SafetyAction(str, Enum):
    NORMAL = "NORMAL"
    MONITOR = "MONITOR"
    ZONE_ALERT = "ZONE_ALERT"
    REASSIGN_TO_COBOT = "REASSIGN_TO_COBOT"
    ESTOP = "EMERGENCY_STOP"


class DecisionLog(Base, TimestampMixin):
    """Immutable audit trail of automated safety and reallocation decisions."""
    __tablename__ = "decision_logs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    site_id: Mapped[str] = mapped_column(String(36), ForeignKey("sites.id"), nullable=False)
    camera_id: Mapped[str] = mapped_column(String(36), ForeignKey("cameras.id"), nullable=False)
    worker_id: Mapped[str] = mapped_column(String(36), ForeignKey("workers.id"), nullable=True)
    zone_id: Mapped[str] = mapped_column(String(36), ForeignKey("safety_zones.id"), nullable=True)

    # Perception & Kinematic Metrics
    fatigue_score: Mapped[float] = mapped_column(Float, nullable=False)
    slump_angle: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    stillness_seconds: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    in_zone: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Decision Engine Output
    action_taken: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), default="info", nullable=False)
    rule_fired: Mapped[str] = mapped_column(String(100), nullable=False)
    engine_version: Mapped[str] = mapped_column(String(50), default="rule_v1", nullable=False)
    execution_latency_ms: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    raw_metrics_json: Mapped[str] = mapped_column(Text, nullable=True)

    worker = relationship("Worker", back_populates="decision_logs")
    camera = relationship("Camera", back_populates="decision_logs")
    zone = relationship("SafetyZone", back_populates="decision_logs")
    explanation = relationship("IncidentExplanation", back_populates="decision", uselist=False, cascade="all, delete-orphan")
    alerts = relationship("SafetyAlert", back_populates="decision", cascade="all, delete-orphan")


class IncidentExplanation(Base, TimestampMixin):
    """Plain-language explainability record generated by LLM or deterministic fallback."""
    __tablename__ = "incident_explanations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    decision_log_id: Mapped[str] = mapped_column(String(36), ForeignKey("decision_logs.id"), nullable=False)
    explanation_text: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(String(50), default="deterministic_fallback", nullable=False)  # llm_anthropic, deterministic_fallback
    osha_report_json: Mapped[str] = mapped_column(Text, nullable=True)

    decision = relationship("DecisionLog", back_populates="explanation")
